SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

FPS_LIMIT = 60

LINE_WIDTH = 2

ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8
ASTEROID_MIN_RADIUS = 20
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_MIN_SPEED = 40
ASTEROID_MAX_SPEED = 100
ASTEROID_MIN_SPAWN_ANGLE = -30
ASTEROID_MAX_SPAWN_ANGLE = 30
ASTEROID_MIN_SPLIT_ANGLE = 20
ASTEROID_MAX_SPLIT_ANGLE = 50
ASTEROID_SPEED_MULTIPLIER = 1.2

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 100
PLAYER_COOLDOWN_TIMER = 0.3

SHOT_RADIUS = 5
